Algoritmo "exe5_2_contador"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vilson dos Santos Oliveira Filho
// Data atual  : 25/03/2022
Var
// Seção de Declarações das variáveis
     contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

  repita
  escreva (contador)
  contador <- contador + 1
  ate (contador > 10)

Fimalgoritmo
