Algoritmo "exe8_parafaca"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Eduardo Costa Gama
// Data atual  : 25/03/2022
Var
// Seção de Declarações das variáveis
     contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...


  para contador de 1 ate 50 faca
  escreva(contador)
  fimpara



Fimalgoritmo
