Algoritmo "multiplica??o"
// Disciplina   : [Linguagem e L?gica de Programa??o]
// Professor   : Hiram Amaral
// Descri??o   : Algoritmo que recebe dois n?meros.
//               Efetua a multiplica??o destes.
//               Exibe o c?lculo e o resultado da multiplica??o.Aqui voc? descreve o que o programa faz! (fun??o)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/03/2022


Var

// Se??o de Declara??es das vari?veis

n1 , n2 , n3, result : real



Inicio

// Se??o de Comandos, procedimento, fun??es, operadores, etc...

//------------------------------------------------------------------------+
// Passando valores iniciais para as vari?veis
//------------------------------------------------------------------------+

n1 <- 0

n2 <- 0

n3 <- 0

result <- 0



//------------------------------------------------------------------------+
// Apresenta??o
//------------------------------------------------------------------------+

escreval ("")

escreval (" Software que realiza a operação multiplicação de números.")

escreval ("")

escreval (" Exibe o cálculo e o resultado desta.")

escreval ("")

escreval ("")



//------------------------------------------------------------------------+
// Entrada de dados
//------------------------------------------------------------------------+

escreva (" 01 Número .....:  ")

leia (n1)

escreval ("")

escreva (" 02 Número .....:  ")

leia (n2)

escreval ("")

escreva (" 03 Número .....:  ")

leia (n3)

escreval ("")



//------------------------------------------------------------------------+
// Exibindo C?LCULO que ser? efetuado
//------------------------------------------------------------------------+

escreval (" Cálculo .......: ", n1, " *", n2,"*", n3)

escreval ("")



//------------------------------------------------------------------------+
// Efetuando C?LCULOS
//------------------------------------------------------------------------+

result <- n1 * n2 * n3



//------------------------------------------------------------------------+
// Sa?da de dados
//------------------------------------------------------------------------+

escreva (" Resultado .....: ", result)



//------------------------------------------------------------------------+
// Pulando linhas
//------------------------------------------------------------------------+

escreval ("")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
escreval ("")
FimAlgoritmo