Algoritmo "exe7_nomecompleto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Eduardo Costa Gama
// Data atual  : 25/03/2022
Var
// Seção de Declarações das variáveis
   nome, snome, ncompleto: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("média: ")
   leia(nome)


Fimalgoritmo